export const types = {
  login: "[Auth] Login",
  logout: "[Auth] Logout",

  uiStartLoading: "[Auth] Start Loading",
  uiFinishLoading: "[Auth] Finish Loading",

  loadRankigPoliticians: "[Ranking] get the data for the ranking",
  rankingUpdate: "[Ranking] update rankig and get new data",

  dataSelectPoliticalParties: "[DataSelect] get the data for the select  politicalParties",
  dataSelectDistricts: "[DataSelect] get the data for the select districts",
  dataSelectLegislatures: "[DataSelect] get the data for the select legislatures",
  dataSelectCommissions: "[DataSelect] get the data for the select commissions",
  dataSelectPolitician: "[DataSelect] get the data for the select politician",

  legislatureAddNew: "[Legislature] New Legislature",
  legislaturesLoad: "[Legislature] Loading Legislatures",
  legislaturesActiveUpdated: "[legislature] Active Updated and Select Legislature",
  legislatureUpdate: "[Legislature] Update Legislature",
  legislatureDelete: "[Legislature] Delete Legislature",
  legislatureLogoutCleaning: "[Legislature] Logout Cleaning",

  commissionAddNew: "[Commission] New commission",
  commissionsLoad: "[Commission] Loading commissions",
  commissionsActiveUpdated: "[Commission] Active Updated and Select commission",
  commissionUpdate: "[Commission] Update commission",
  commissionDelete: "[Commission] Delete commission",
  commissionLogoutCleaning: "[Commission] Logout Cleaning",

  assignCommissionAddNew: "[assign-commissions] New Asignacion de commission",
  assignCommissionLoad: "[assign-commissions] Loading commissions",
  assignCommissionActiveUpdated: "[assign-commissions] Active Updated and Select commission",
  assignCommissionUpdate: "[assign-commissions] Update commission",
  assignCommissionDelete: "[assign-commissions] Delete commission",
  assignCommissionLogoutCleaning: "[assign-commissions] Logout Cleaning",

  politicalPartyAddNew: "[PoliticalParty] New politicalParty",
  politicalPartiesLoad: "[PoliticalParties] Loading politicalParties",
  politicalPartiesActiveUpdated: "[PoliticalParty] Active Updated and Select PoliticalParty",
  politicalPartyUpdate: "[PoliticalParty] Update PoliticalParty",
  politicalPartyDelete: "[politicalParty] Delete politicalParty",
  politicalPartiesLogoutCleaning: "[politicalParties] Logout Cleaning",

  districtsLoad: "[District] Loading districts",
  districtAddNew: "[District] New district",
  districtActiveUpdated: "[District] Active Updated and Select district",
  districtShowSections: "[District] Show sections the district",
  districtUpdate: "[District] Update district",
  districtDelete: "[District] Delete district",
  districtResetState: "[District] Reset state district",

  politiciansLoad: "[Politician] Loading politicians",
  politicianAddNew: "[Politician] Add New politician",
  politicianActiveUpdated: "[Politician] Active Updated and select politician",
  politicianUpdate: "[Politician] Update politician",
  politicianShow: "[Politician] Show detail politiian",
  politicianDelete: "[Politician] Delete politician",
  politicianResetState: "[Politician] Reset state politician",

  globalSettingsLoad: "[Global-Settings] Loading Global-Settings",
  globalSettingsLoadAddNew: "[Global-Settings] Add New Global-Setting",
  globalSettingsLoadActiveUpdated: "[Global-Settings] Active Updated and select Global-Settings",
  globalSettingsLoadUpdate: "[Global-Settings] Update Global-Settings",
  globalSettingsLoadDelete: "[Global-Settings] Delete Global-Settings",
  globalSettingsLoadResetState: "[Global-Settings] Reset state Global-Settings",

  usersLoad: "[users] Loading users",
  usersAddNew: "[users] Add Newusers",
  usersActiveUpdated: "[users] Active Updated and select users",
  usersUpdate: "[users] Update users",
  usersDelete: "[users] Delete users",
  usersResetState: "[users] Reset state users",
  usersLogoutCleaning: "[assign-commissions] Logout Cleaning",

  permissionsLoad: "[permissions] Loading Permissions",
  permissionsAddNew: "[permissions] Add new Permission",
  permissionsActiveUpdated: "[permissions] Active Updated and select permissions",
  permissionsUpdate: "[permissions] Update permissions",
  permissionsDelete: "[permissions] Delete permissions",

  rolesLoad: "[roles] Loading Roles",
  rolesAddNew: "[roles] Add new Rol",
  rolesActiveUpdated: "[roles] Active Updated and select roles",
  rolesUpdate: "[roles] Update roles",
  rolesDelete: "[roles] Delete roles",
};
