/* import dotenv from "dotenv";
dotenv.config(); */

//console.log(process.env);
const IS_PRODUCTION = process.env.REACT_APP_IS_PRODUCTION === "true";

const exportDefaultValues = {
  REACT_APP_FIREBASE_API_KEY: IS_PRODUCTION ? process.env.REACT_APP_FIREBASE_API_KEY : process.env.REACT_APP_DEV_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN: IS_PRODUCTION ? process.env.REACT_APP_FIREBASE_AUTH_DOMAIN : process.env.REACT_APP_DEV_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID: IS_PRODUCTION ? process.env.REACT_APP_FIREBASE_PROJECT_ID : process.env.REACT_APP_DEV_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET: IS_PRODUCTION ? process.env.REACT_APP_FIREBASE_STORAGE_BUCKET : process.env.REACT_APP_DEV_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: IS_PRODUCTION ? process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID : process.env.REACT_APP_DEV_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID: IS_PRODUCTION ? process.env.REACT_APP_FIREBASE_APP_ID : process.env.REACT_APP_DEV_FIREBASE_APP_ID,
};

export default exportDefaultValues;
